### ISSUE TITLE
Update publish button

### ISSUE THREAD

**Issue by literarymachine** [hbz/skohub-editor#12]
The button at the bottom of the form should be renamed to `Publish`, and there should be some kind of feedback after pushing it (for now, an `alert` would do).

**Comment by acka47** [comment]
Fixed. Closing.

**Comment by acka47** [comment]
Looks like not everything is deployed to production yet (only the re-labeld button but no notification there). Re-openening for deploying.

**Comment by literarymachine** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/149825/70152117-ed524800-16ac-11ea-9145-a2e954349002.png)

Are you sure you added a subject?

**Comment by acka47** [comment]
You are right, it works. Closing.
